from matrix import *

print('Осуществляется ввод коэффициентов: ')
matrix_сoef = matrix(random=1) # Необходимо ввести матрицу NxN
print('Осуществляется ввод свободных членов: ')
vector_c = matrix(random=1) # Необходимо ввести матрицу Nx1

matrix_added = []
for j in range(len(vector_c)):
    matrix_added.append(matrix_сoef[j]+vector_c[j])
input_Jacobi = method_Jacobi(matrix_сoef,vector_c)
input_Gauss = gssjrdn(matrix_сoef,vector_c)
input_Gauss_fr = frkgssjrdn(matrix_сoef,vector_c)
print('Метод Якоби: ')
print('Введенная матрица: ')
print('\n')
print(*matrix_added, sep='\n')
print('\n')
print('Обратная матрица: ')
print('\n')
_ = reverse_matrix(matrix_сoef)
print(*_, sep='\n')
print('\n')
print('Решение методом Якоби: ')
print('\n')
print(input_Jacobi[2])
print('Обусловленность введеной системы:')
print('\n')
print(cord(matrix_сoef))
if cord(matrix_сoef) > 10:
    print("Алгоритм Гаусса")
    print('Введенная матрица: ')
    print('\n')
    print(input_Gauss[0],  sep='\n')
    print('\n')
    print('Обратная матрица: ')
    print('\n')
    print(input_Gauss[1],  sep='\n')
    print('\n')
    print('Решение методом Гауса: ')
    print('\n')
    print(input_Gauss[2])
    print('Обусловленность введеной системы:')
    print('\n')
    print(cord(matrix_сoef))
    if cord(matrix_сoef) > 10:
        print("Алгоритм Гаусса c fractions")
        print('Введенная матрица: ')
        print('\n')
        print(input_Gauss_fr[0],  sep='\n')
        print('\n')
        print('Обратная матрица: ')
        print('\n')
        print(input_Gauss_fr[1],  sep='\n')
        print('\n')
        print('Решение методом Гауса с дробями: ')
        print('\n')
        print(input_Gauss_fr[2])
